### PR TITLE
Add fixed lambda/forward stepwise tests comparing w/ R output

### PR DESCRIPTION
**Pull request by bnaul**
Forward stepwise p-values don't match yet

### CODE REVIEW

**Comment by jonathan-taylor** [comment]
The test failed because of a bug in the R code, addressed here: https://github.com/selective-inference/R-software/pull/12

Also R code has reported one-sided p-values by default which needed a modifiction of forward_step. A fix is proposed in this PR: https://github.com/bnaul/selective-inference/pull/1

**Comment by bnaul** [comment]
I just upgraded my R to 3.2.4 and it segfaults when I try to run anything with `rpy2`...so for now I'll take your word for it I guess :+1:.

**Comment by jonathan-taylor** [comment]
Aha, I will add a skip decorator when importing rpy2 fails. Can't fix the
segfault though :)

On Wed, Apr 6, 2016 at 6:06 PM, Brett Naul <notifications@github.com> wrote:

> I just upgraded my R to 3.2.4 and it segfaults when I try to run anything
> with rpy2...so for now I'll take your word for it I guess [image: :+1:].
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/selective-inference/Python-software/pull/6#issuecomment-206640634>
>



-- 
Jonathan Taylor
Dept. of Statistics
Sequoia Hall, 137
390 Serra Mall
Stanford, CA 94305
Tel:   650.723.9230
Fax:   650.725.8977
Web: http://www-stat.stanford.edu/~jtaylo

**Comment by jonathan-taylor** [comment]
I added a check to see if rpy2 is available as well as tests of the Cox and
logistic models.

One test still failing but I think it is inconsistency of which p-value is
reported in R version.

On Wed, Apr 6, 2016 at 11:01 PM, Jonathan Taylor <
jonathan.taylor@stanford.edu> wrote:

> Aha, I will add a skip decorator when importing rpy2 fails. Can't fix the
> segfault though :)
>
> On Wed, Apr 6, 2016 at 6:06 PM, Brett Naul <notifications@github.com>
> wrote:
>
>> I just upgraded my R to 3.2.4 and it segfaults when I try to run anything
>> with rpy2...so for now I'll take your word for it I guess [image: :+1:].
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/selective-inference/Python-software/pull/6#issuecomment-206640634>
>>
>
>
>
> --
> Jonathan Taylor
> Dept. of Statistics
> Sequoia Hall, 137
> 390 Serra Mall
> Stanford, CA 94305
> Tel:   650.723.9230
> Fax:   650.725.8977
> Web: http://www-stat.stanford.edu/~jtaylo
>



-- 
Jonathan Taylor
Dept. of Statistics
Sequoia Hall, 137
390 Serra Mall
Stanford, CA 94305
Tel:   650.723.9230
Fax:   650.725.8977
Web: http://www-stat.stanford.edu/~jtaylo

**Pull request merged**
